import json
from pathlib import Path

def main():
    with open('notebooks/13_mobilenetv2_bilstm_attention_pooling_experiment.ipynb', 'r') as f:
        nb = json.load(f)

    # Cell 0: Header markdown
    nb['cells'][0]['source'] = [
        '# 13 - EfficientNetB0 + BiLSTM with Learnable Temporal Attention Pooling\n',
        '## Tai Phake Visual Speech Recognition (VSR) Project\n',
        '\n',
        '### Architecture Strategy: Recurrent Inductive Bias with Attention Pooling for Small Datasets\n',
        '\n',
        '**Motivation & Background:**\n',
        'For limited-data regimes (~330 baseline utterance samples in Tai Phake VSR), multi-head self-attention Transformers lack sequence-specific inductive bias and possess excessive parameter capacity, making them prone to overfitting.\n',
        '\n',
        'Bidirectional LSTMs (BiLSTM) impose an explicit sequential inductive bias across frames, capturing temporal lip motion transitions efficiently without requiring massive pretraining corpora. Furthermore, replacing uniform average pooling with **Learnable Temporal Attention Pooling** enables the network to adaptively weigh phonetically discriminative viseme frames (e.g., maximum mouth opening or salient articulation) while downweighting resting/closed-mouth boundary frames.\n',
        '\n',
        '**Model Architecture:**\n',
        '1. **Visual Frontend**: Pretrained EfficientNetB0 (`include_top=False`, `pooling=\'avg\'`, ImageNet weights, frozen in Stage 1) extracting 1,280-dim feature vectors per frame.\n',
        '2. **Linear Projection & Normalization**: TimeDistributed Dense projection to 256-dim features with LayerNormalization.\n',
        '3. **Temporal Modeling**: Bidirectional LSTM (128 units per direction, 256 total bidirectional output dimension, `return_sequences=True`, dropout=0.2).\n',
        '4. **Temporal Attention Pooling**: Learnable dense scoring + softmax attention weighting across the 30 temporal timesteps ($T=30$) to compute a weighted context vector.\n',
        '5. **Classification Head**: Dropout (0.4) + Dense(11, activation=\'softmax\') targeting digits $d_0$ through $d_{10}$.\n',
        '\n',
        '**Training Protocol:**\n',
        '- **Two-Stage Fine-Tuning**: Stage 1 freezes the EfficientNetB0 backbone entirely (learning rate $1\\times 10^{-4}$); Stage 2 unfreezes the top 20% of EfficientNetB0 with BatchNormalization kept frozen (learning rate $1\\times 10^{-5}$).\n',
        '- **Loss Formulation**: Sparse label smoothing ($0.1$) for enhanced generalization.\n',
        '- **Dataset Target**: 80/20 split dataset mode (`DATASET_MODE = "80_20"`).\n'
    ]

    # Cell 1: Keep DATASET_MODE = "80_20"
    nb['cells'][1]['source'] = [
        '# =============================================================================\n',
        '# EXPERIMENT CONFIGURATION\n',
        '# =============================================================================\n',
        '\n',
        'DATASET_MODE = "80_20"\n',
        '# Options:\n',
        '#   "80_20"   -> 24 base speakers train + 6 base speakers validation\n',
        '#   "100_3_3" -> use the existing train/val/test processed split\n'
    ]

    # Cell 4: Markdown for config
    nb['cells'][4]['source'] = [
        '## 3. Configuration\n',
        'Defining deterministic random seeds, image and sequence parameters, BiLSTM and Attention Pooling hyperparameters, and two-stage training settings.\n'
    ]

    # Cell 5: Configuration & Hyperparameters
    nb['cells'][5]['source'] = [
        '# Section 3: Configuration & Hyperparameters\n',
        'SEED = 42\n',
        '\n',
        '# Reproducibility seeding\n',
        'random.seed(SEED)\n',
        'np.random.seed(SEED)\n',
        'tf.random.set_seed(SEED)\n',
        'os.environ["PYTHONHASHSEED"] = str(SEED)\n',
        '\n',
        '# Sequence & Image Specifications (Method D standard)\n',
        'NUM_CLASSES = 11\n',
        'NUM_FRAMES = 30\n',
        'FRAME_WIDTH = 96\n',
        'FRAME_HEIGHT = 96\n',
        'FRAME_CHANNELS = 3\n',
        'BATCH_SIZE = 16\n',
        '\n',
        '# BiLSTM & Attention Pooling Architecture Hyperparameters\n',
        'PROJECTION_DIM = 256\n',
        'LSTM_UNITS = 128          # Bidirectional -> 256 total output feature dimension\n',
        'LSTM_DROPOUT = 0.2\n',
        'HEAD_DROPOUT = 0.4\n',
        '\n',
        '# Two-Stage Training Hyperparameters\n',
        'STAGE1_LR = 1e-4\n',
        'STAGE1_MAX_EPOCHS = 40\n',
        'STAGE1_PATIENCE = 8\n',
        '\n',
        'STAGE2_LR = 1e-5\n',
        'STAGE2_MAX_EPOCHS = 25\n',
        'STAGE2_PATIENCE = 6\n',
        'FINE_TUNE_FRACTION = 0.20  # Fine-tune last 20% of EfficientNetB0\n',
        'LABEL_SMOOTHING = 0.1      # Sparse-compatible label smoothing\n',
        '\n',
        '# Target Digit Classes (d0 through d10)\n',
        'DIGIT_CLASSES = [f"d{i}" for i in range(NUM_CLASSES)]\n',
        'CLASS_TO_ID = {d: i for i, d in enumerate(DIGIT_CLASSES)}\n',
        'ID_TO_CLASS = {i: d for i, d in enumerate(DIGIT_CLASSES)}\n',
        '\n',
        'print("=" * 80)\n',
        'print("EXPERIMENT CONFIGURATION & HYPERPARAMETERS")\n',
        'print("=" * 80)\n',
        'print(f"Dataset Mode                 : {DATASET_MODE}")\n',
        'print(f"Random Seed                  : {SEED}")\n',
        'print(f"Target Digit Classes ({len(DIGIT_CLASSES)})   : {DIGIT_CLASSES}")\n',
        'print(f"Input Sequence Shape         : ({NUM_FRAMES} frames, {FRAME_HEIGHT}x{FRAME_WIDTH}, {FRAME_CHANNELS} channels)")\n',
        'print(f"Batch Size                   : {BATCH_SIZE}")\n',
        'print(f"Projection Dimension         : {PROJECTION_DIM}")\n',
        'print(f"BiLSTM Hidden Units          : {LSTM_UNITS} per direction (Total: {LSTM_UNITS * 2})")\n',
        'print(f"LSTM Dropout                 : {LSTM_DROPOUT}")\n',
        'print(f"Temporal Pooling             : Learnable Temporal Attention Pooling")\n',
        'print(f"Head Dropout                 : {HEAD_DROPOUT}")\n',
        'print(f"Label Smoothing              : {LABEL_SMOOTHING}")\n',
        'print(f"Stage 1 Setup                : Adam(lr={STAGE1_LR}), max_epochs={STAGE1_MAX_EPOCHS}, patience={STAGE1_PATIENCE}")\n',
        'print(f"Stage 2 Setup                : Adam(lr={STAGE2_LR}), max_epochs={STAGE2_MAX_EPOCHS}, patience={STAGE2_PATIENCE}, unfreeze={int(FINE_TUNE_FRACTION*100)}%")\n',
        'print("=" * 80)\n'
    ]

    # Cell 6: Markdown for dataset paths
    nb['cells'][6]['source'] = [
        '## 4. Dataset Paths\n',
        'Configuring paths for the active Method D processed dataset (`data/processed`) and creating a dedicated output directory for this EfficientNetB0 + BiLSTM Attention Pooling experiment (`results/efficientnetb0_bilstm_attention_pooling_{DATASET_MODE}`).\n'
    ]

    # Cell 7: Dataset paths code
    nb['cells'][7]['source'] = [
        '# Section 4: Dataset Paths Configuration\n',
        'NOTEBOOK_DIR = Path.cwd()\n',
        'PROJECT_ROOT = NOTEBOOK_DIR.parent if NOTEBOOK_DIR.name == "notebooks" else NOTEBOOK_DIR\n',
        '\n',
        'DATA_DIR = PROJECT_ROOT / "data" / "processed"\n',
        'TRAIN_DIR = DATA_DIR / "train"\n',
        'VAL_DIR = DATA_DIR / "val"\n',
        'TEST_DIR = DATA_DIR / "test"\n',
        '\n',
        '# Dedicated Results Directory per Dataset Mode\n',
        'RESULTS_DIR = PROJECT_ROOT / "results" / f"efficientnetb0_bilstm_attention_pooling_{DATASET_MODE}"\n',
        'RESULTS_DIR.mkdir(parents=True, exist_ok=True)\n',
        '\n',
        'test_path_str = str(TEST_DIR) if DATASET_MODE == "100_3_3" else "DISABLED"\n',
        '\n',
        'print("=" * 80)\n',
        'print("DIRECTORY & EXPERIMENT CONFIGURATION")\n',
        'print("=" * 80)\n',
        'print(f"Dataset Mode: {DATASET_MODE}")\n',
        'print(f"Train:        {TRAIN_DIR}")\n',
        'print(f"Validation:   {VAL_DIR}")\n',
        'print(f"Test:         {test_path_str}")\n',
        'print(f"Results:      {RESULTS_DIR}")\n',
        'print("=" * 80)\n'
    ]

    # Cell 20: Markdown for End-to-End Model Assembly
    nb['cells'][20]['source'] = [
        '## 11. EfficientNetB0 + BiLSTM with Temporal Attention Pooling Model\n',
        'Building the complete end-to-end architecture:\n',
        '```\n',
        'Input: (30, 96, 96, 3)\n',
        '   ↓\n',
        'TimeDistributed EfficientNetB0 (preprocess_input + ImageNet backbone)\n',
        '   ↓\n',
        '1280-dimensional feature vector per frame\n',
        '   ↓\n',
        'Dense(256) Projection + LayerNormalization\n',
        '   ↓\n',
        'Bidirectional LSTM(128 units, return_sequences=True, dropout=0.2)\n',
        '   ↓ (30, 256)\n',
        'Learnable Temporal Attention Pooling (Dense(1) -> Softmax(axis=1) -> Weighted Sum)\n',
        '   ↓ (256)\n',
        'Dropout(0.4)\n',
        '   ↓\n',
        'Dense(11, activation="softmax")\n',
        '```\n'
    ]

    # Cell 21: Model Assembly code
    nb['cells'][21]['source'] = [
        '# Section 11: End-to-End Model Assembly\n',
        'def get_efficientnetb0_backbone():\n',
        '    """\n',
        '    Builds the EfficientNetB0 visual feature extractor.\n',
        '    """\n',
        '    cnn = keras.applications.EfficientNetB0(\n',
        '        input_shape=(FRAME_HEIGHT, FRAME_WIDTH, FRAME_CHANNELS),\n',
        '        include_top=False,\n',
        '        weights="imagenet",\n',
        '        pooling="avg"\n',
        '    )\n',
        '    preprocess_fn = keras.applications.efficientnet.preprocess_input\n',
        '    return cnn, preprocess_fn\n',
        '\n',
        'def build_efficientnet_bilstm_attention_pooling():\n',
        '    """\n',
        '    Constructs the complete EfficientNetB0 + BiLSTM with Learnable Attention Pooling architecture.\n',
        '    """\n',
        '    cnn, preprocess_fn = get_efficientnetb0_backbone()\n',
        '\n',
        '    # Input: (batch, 30, 96, 96, 3)\n',
        '    inputs = keras.layers.Input(\n',
        '        shape=(NUM_FRAMES, FRAME_HEIGHT, FRAME_WIDTH, FRAME_CHANNELS),\n',
        '        name="lip_sequence_input"\n',
        '    )\n',
        '\n',
        '    # 1. Image preprocessing inside the Keras computational graph\n',
        '    x = keras.layers.TimeDistributed(\n',
        '        keras.layers.Lambda(preprocess_fn),\n',
        '        name="efficientnetb0_preprocess"\n',
        '    )(inputs)\n',
        '\n',
        '    # 2. Frame-level feature extraction via EfficientNetB0 (yields 1280 features per frame)\n',
        '    x = keras.layers.TimeDistributed(cnn, name="efficientnetb0_cnn")(x)  # (batch, 30, 1280)\n',
        '\n',
        '    # 3. Dense Projection to feature dimension 256\n',
        '    x = keras.layers.TimeDistributed(\n',
        '        keras.layers.Dense(PROJECTION_DIM, use_bias=False),\n',
        '        name="projection_dense"\n',
        '    )(x)  # (batch, 30, 256)\n',
        '    x = keras.layers.LayerNormalization(epsilon=1e-6, name="projection_ln")(x)\n',
        '\n',
        '    # 4. Bidirectional LSTM Sequence Modeling (128 units each direction -> 256 dim)\n',
        '    x = keras.layers.Bidirectional(\n',
        '        keras.layers.LSTM(LSTM_UNITS, return_sequences=True, dropout=LSTM_DROPOUT),\n',
        '        name="bilstm"\n',
        '    )(x)  # (batch, 30, 256)\n',
        '\n',
        '    # 5. Learnable Temporal Attention Pooling\n',
        '    attn_scores = keras.layers.Dense(1, use_bias=True, name="temporal_attn_score")(x)  # (batch, 30, 1)\n',
        '    attn_weights = keras.layers.Softmax(axis=1, name="temporal_attn_weights")(attn_scores)  # (batch, 30, 1)\n',
        '    x = keras.layers.Lambda(\n',
        '        lambda tensors: tf.reduce_sum(tensors[0] * tensors[1], axis=1),\n',
        '        name="temporal_attention_pooling"\n',
        '    )([x, attn_weights])  # (batch, 256)\n',
        '\n',
        '    # 6. Classification Head\n',
        '    x = keras.layers.Dropout(HEAD_DROPOUT, name="head_dropout")(x)\n',
        '    outputs = keras.layers.Dense(NUM_CLASSES, activation="softmax", name="digit_classifier")(x)\n',
        '\n',
        '    model = keras.Model(inputs=inputs, outputs=outputs, name="EfficientNetB0_BiLSTM_AttentionPooling")\n',
        '    return model, cnn\n',
        '\n',
        'print("Architecture builders defined.")\n'
    ]

    # Cell 22: Markdown Model Summary
    nb['cells'][22]['source'] = [
        '## 12. Model Summary\n',
        'Instantiating the model, inspecting its layer hierarchy, and verifying a forward pass on a synthetic input batch.\n'
    ]

    # Cell 23: Code Model Summary
    nb['cells'][23]['source'] = [
        '# Section 12: Model Summary & Forward Pass Verification\n',
        'model, cnn = build_efficientnet_bilstm_attention_pooling()\n',
        '\n',
        'print("=" * 80)\n',
        'print("             EFFICIENTNETB0 + BiLSTM + ATTENTION POOLING ARCHITECTURE")\n',
        'print("=" * 80)\n',
        'model.summary()\n',
        '\n',
        '# Forward pass validation on a dummy input batch\n',
        'dummy_batch = tf.random.uniform((2, NUM_FRAMES, FRAME_HEIGHT, FRAME_WIDTH, FRAME_CHANNELS), 0.0, 255.0)\n',
        'dummy_out = model(dummy_batch, training=False)\n',
        '\n',
        'assert dummy_out.shape == (2, NUM_CLASSES), f"Unexpected output shape: {dummy_out.shape}"\n',
        'print(f"\\n[SUCCESS] Forward pass verification passed! Output shape: {dummy_out.shape} for input (2, 30, 96, 96, 3)")\n'
    ]

    # Cell 24: Markdown Stage 1
    nb['cells'][24]['source'] = [
        '## 13. Stage 1 Training: Frozen EfficientNetB0\n',
        '- EfficientNetB0 backbone is **completely frozen** (`trainable = False`).\n',
        '- BiLSTM, Projection layer, Attention Pooling, and classification head are trainable.\n',
        '- Optimizer: **Adam** (learning rate = $1\\times 10^{-4}$).\n',
        '- Loss: **Sparse-label-compatible Label Smoothing** ($0.1$).\n',
        '- Maximum epochs: 40, EarlyStopping patience = 8 monitoring `val_loss`.\n',
        '- ModelCheckpoint preserves the best Stage 1 weights.\n'
    ]

    # Cell 25: Code Stage 1
    nb['cells'][25]['source'] = [
        '# Section 13: Stage 1 Training (Frozen EfficientNetB0)\n',
        'def sparse_label_smoothing_loss(smoothing=LABEL_SMOOTHING):\n',
        '    """\n',
        '    Sparse-label-compatible cross-entropy loss with label smoothing.\n',
        '    Matches the formulation from the baseline BiLSTM experiment.\n',
        '    """\n',
        '    def loss_fn(y_true, y_pred):\n',
        '        num_classes = tf.shape(y_pred)[-1]\n',
        '        y_true = tf.cast(y_true, tf.int32)\n',
        '\n',
        '        y_true_one_hot = tf.one_hot(\n',
        '            y_true,\n',
        '            depth=num_classes\n',
        '        )\n',
        '\n',
        '        y_true_smooth = (\n',
        '            y_true_one_hot * (1.0 - smoothing)\n',
        '            + smoothing / tf.cast(num_classes, tf.float32)\n',
        '        )\n',
        '\n',
        '        return tf.keras.losses.categorical_crossentropy(\n',
        '            y_true_smooth,\n',
        '            y_pred\n',
        '        )\n',
        '\n',
        '    return loss_fn\n',
        '\n',
        'def freeze_all_cnn_layers(backbone):\n',
        '    backbone.trainable = False\n',
        '    for layer in backbone.layers:\n',
        '        layer.trainable = False\n',
        '\n',
        '# Freeze entire CNN backbone for Stage 1\n',
        'freeze_all_cnn_layers(cnn)\n',
        '\n',
        '# Compile model for Stage 1\n',
        'model.compile(\n',
        '    optimizer=keras.optimizers.Adam(learning_rate=STAGE1_LR),\n',
        '    loss=sparse_label_smoothing_loss(LABEL_SMOOTHING),\n',
        '    metrics=["accuracy"]\n',
        ')\n',
        '\n',
        'stage1_weights_path = RESULTS_DIR / "efficientnetb0_bilstm_attention_pooling_stage1_best.weights.h5"\n',
        '\n',
        'checkpoint1 = keras.callbacks.ModelCheckpoint(\n',
        '    stage1_weights_path,\n',
        '    monitor="val_loss",\n',
        '    save_best_only=True,\n',
        '    save_weights_only=True,\n',
        '    verbose=1\n',
        ')\n',
        '\n',
        'early1 = keras.callbacks.EarlyStopping(\n',
        '    monitor="val_loss",\n',
        '    patience=STAGE1_PATIENCE,\n',
        '    restore_best_weights=True,\n',
        '    verbose=1\n',
        ')\n',
        '\n',
        'print("=" * 80)\n',
        'print(f"STARTING STAGE 1 TRAINING: Frozen EfficientNetB0 (lr={STAGE1_LR}, max_epochs={STAGE1_MAX_EPOCHS})")\n',
        'print(f"Train samples: {len(X_train):,} | Validation samples: {len(X_val):,}")\n',
        'print("=" * 80)\n',
        '\n',
        't_stage1_start = time.time()\n',
        'history1 = model.fit(\n',
        '    X_train,\n',
        '    y_train,\n',
        '    validation_data=(X_val, y_val),\n',
        '    epochs=STAGE1_MAX_EPOCHS,\n',
        '    batch_size=BATCH_SIZE,\n',
        '    shuffle=True,\n',
        '    callbacks=[checkpoint1, early1],\n',
        '    verbose=1\n',
        ')\n',
        'stage1_elapsed = time.time() - t_stage1_start\n',
        '\n',
        '# Ensure best weights are restored\n',
        'if stage1_weights_path.exists():\n',
        '    model.load_weights(stage1_weights_path)\n',
        '\n',
        'stage1_best_epoch = int(np.argmin(history1.history["val_loss"]) + 1)\n',
        'stage1_best_val_acc = float(max(history1.history["val_accuracy"]))\n',
        'stage1_best_val_loss = float(min(history1.history["val_loss"]))\n',
        '\n',
        'print("-" * 80)\n',
        'print(f"Stage 1 Completed in {stage1_elapsed:.2f}s")\n',
        'print(f"Stage 1 Best Epoch            : {stage1_best_epoch}")\n',
        'print(f"Stage 1 Best Validation Loss  : {stage1_best_val_loss:.4f}")\n',
        'print(f"Stage 1 Best Validation Acc   : {stage1_best_val_acc * 100:.2f}%")\n',
        'print("=" * 80)\n'
    ]

    # Cell 26: Markdown Stage 2
    nb['cells'][26]['source'] = [
        '## 14. Stage 2 Fine-Tuning: Unfreezing Last 20% of EfficientNetB0\n',
        '- Reload best Stage 1 weights.\n',
        '- Unfreeze the **top 20%** of EfficientNetB0 layers (`fraction=0.20`), keeping all `BatchNormalization` layers frozen for training stability.\n',
        '- BiLSTM sequence model, attention pooling, and classification head remain trainable.\n',
        '- Optimizer: **Adam** (learning rate = $1\\times 10^{-5}$).\n',
        '- Loss: **Sparse-label-compatible Label Smoothing** ($0.1$).\n',
        '- Maximum epochs: 25, EarlyStopping patience = 6 monitoring `val_loss`.\n',
        '- ModelCheckpoint preserves the best Stage 2 weights.\n'
    ]

    # Cell 27: Code Stage 2
    nb['cells'][27]['source'] = [
        '# Section 14: Stage 2 Fine-Tuning (Top 20% EfficientNetB0, BatchNorm Frozen)\n',
        '# 1. Reload best Stage-1 weights\n',
        'if stage1_weights_path.exists():\n',
        '    model.load_weights(stage1_weights_path)\n',
        '    print("Reloaded best Stage 1 weights.")\n',
        '\n',
        'def unfreeze_last_fraction(backbone, fraction=FINE_TUNE_FRACTION):\n',
        '    # Freeze all layers first\n',
        '    for layer in backbone.layers:\n',
        '        layer.trainable = False\n',
        '\n',
        '    total_layers = len(backbone.layers)\n',
        '    start_index = int(total_layers * (1.0 - fraction))\n',
        '\n',
        '    for layer in backbone.layers[start_index:]:\n',
        '        # Keep BatchNormalization frozen for training stability\n',
        '        if not isinstance(layer, keras.layers.BatchNormalization):\n',
        '            layer.trainable = True\n',
        '\n',
        '# Unfreeze top 20% of EfficientNetB0\n',
        'unfreeze_last_fraction(cnn, fraction=FINE_TUNE_FRACTION)\n',
        '\n',
        '# Re-compile with fine-tuning learning rate (1e-5)\n',
        'model.compile(\n',
        '    optimizer=keras.optimizers.Adam(learning_rate=STAGE2_LR),\n',
        '    loss=sparse_label_smoothing_loss(LABEL_SMOOTHING),\n',
        '    metrics=["accuracy"]\n',
        ')\n',
        '\n',
        'stage2_trainable_params = int(np.sum([np.prod(v.shape) for v in model.trainable_weights]))\n',
        'print(f"Trainable parameters during Stage 2 Fine-Tuning: {stage2_trainable_params:,}")\n',
        '\n',
        'stage2_weights_path = RESULTS_DIR / "efficientnetb0_bilstm_attention_pooling_stage2_best.weights.h5"\n',
        '\n',
        'checkpoint2 = keras.callbacks.ModelCheckpoint(\n',
        '    stage2_weights_path,\n',
        '    monitor="val_loss",\n',
        '    save_best_only=True,\n',
        '    save_weights_only=True,\n',
        '    verbose=1\n',
        ')\n',
        '\n',
        'early2 = keras.callbacks.EarlyStopping(\n',
        '    monitor="val_loss",\n',
        '    patience=STAGE2_PATIENCE,\n',
        '    restore_best_weights=True,\n',
        '    verbose=1\n',
        ')\n',
        '\n',
        'print("=" * 80)\n',
        'print(f"STARTING STAGE 2 FINE-TUNING (lr={STAGE2_LR}, max_epochs={STAGE2_MAX_EPOCHS})")\n',
        'print("=" * 80)\n',
        '\n',
        't_stage2_start = time.time()\n',
        'history2 = model.fit(\n',
        '    X_train,\n',
        '    y_train,\n',
        '    validation_data=(X_val, y_val),\n',
        '    epochs=STAGE2_MAX_EPOCHS,\n',
        '    batch_size=BATCH_SIZE,\n',
        '    shuffle=True,\n',
        '    callbacks=[checkpoint2, early2],\n',
        '    verbose=1\n',
        ')\n',
        'stage2_elapsed = time.time() - t_stage2_start\n',
        '\n',
        '# Ensure best fine-tuned weights are restored\n',
        'if stage2_weights_path.exists():\n',
        '    model.load_weights(stage2_weights_path)\n',
        '\n',
        'stage2_best_epoch = int(np.argmin(history2.history["val_loss"]) + 1)\n',
        'stage2_best_val_acc = float(max(history2.history["val_accuracy"]))\n',
        'stage2_best_val_loss = float(min(history2.history["val_loss"]))\n',
        '\n',
        'print("-" * 80)\n',
        'print(f"Stage 2 Completed in {stage2_elapsed:.2f}s")\n',
        'print(f"Stage 2 Best Epoch            : {stage2_best_epoch}")\n',
        'print(f"Stage 2 Best Validation Loss  : {stage2_best_val_loss:.4f}")\n',
        'print(f"Stage 2 Best Validation Acc   : {stage2_best_val_acc * 100:.2f}%")\n',
        'print("=" * 80)\n'
    ]

    # Cell 29: Plot titles in training curves
    nb['cells'][29]['source'] = [
        '# Section 15: Training History Compilation & Visualization\n',
        'h1 = history1.history\n',
        'h2 = history2.history\n',
        '\n',
        'combined_history = {\n',
        '    "epoch": list(range(1, len(h1["loss"]) + len(h2["loss"]) + 1)),\n',
        '    "stage": ["Stage 1"] * len(h1["loss"]) + ["Stage 2"] * len(h2["loss"]),\n',
        '    "train_loss": h1["loss"] + h2["loss"],\n',
        '    "val_loss": h1["val_loss"] + h2["val_loss"],\n',
        '    "train_accuracy": h1["accuracy"] + h2["accuracy"],\n',
        '    "val_accuracy": h1["val_accuracy"] + h2["val_accuracy"],\n',
        '}\n',
        'df_history = pd.DataFrame(combined_history)\n',
        'history_csv_path = RESULTS_DIR / "training_history.csv"\n',
        'df_history.to_csv(history_csv_path, index=False)\n',
        'print(f"Full training history saved to: {history_csv_path}")\n',
        '\n',
        'stage1_end = len(h1["loss"])\n',
        '\n',
        '# Plotting curves\n',
        'fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n',
        '\n',
        '# Loss curve\n',
        'ax1.plot(df_history["epoch"], df_history["train_loss"], label="Train Loss", color="#1f77b4", linewidth=2)\n',
        'ax1.plot(df_history["epoch"], df_history["val_loss"], label="Val Loss", color="#ff7f0e", linewidth=2)\n',
        'ax1.axvline(x=stage1_end + 0.5, color="gray", linestyle="--", alpha=0.7, label="Stage 1 / Stage 2 Boundary")\n',
        'ax1.set_title("EfficientNetB0 + BiLSTM (Attn Pooling): Loss Curves", fontsize=13, fontweight="bold")\n',
        'ax1.set_xlabel("Epoch", fontsize=11)\n',
        'ax1.set_ylabel("Loss", fontsize=11)\n',
        'ax1.legend(loc="upper right")\n',
        'ax1.grid(True, alpha=0.3)\n',
        '\n',
        '# Accuracy curve\n',
        'ax2.plot(df_history["epoch"], df_history["train_accuracy"], label="Train Accuracy", color="#2ca02c", linewidth=2)\n',
        'ax2.plot(df_history["epoch"], df_history["val_accuracy"], label="Val Accuracy", color="#d62728", linewidth=2)\n',
        'ax2.axvline(x=stage1_end + 0.5, color="gray", linestyle="--", alpha=0.7, label="Stage 1 / Stage 2 Boundary")\n',
        'ax2.set_title("EfficientNetB0 + BiLSTM (Attn Pooling): Accuracy Curves", fontsize=13, fontweight="bold")\n',
        'ax2.set_xlabel("Epoch", fontsize=11)\n',
        'ax2.set_ylabel("Accuracy", fontsize=11)\n',
        'ax2.legend(loc="lower right")\n',
        'ax2.grid(True, alpha=0.3)\n',
        '\n',
        'plt.tight_layout()\n',
        'curves_path = RESULTS_DIR / "training_history_curves.png"\n',
        'plt.savefig(curves_path, dpi=200)\n',
        'plt.show()\n',
        'print(f"Training curves saved to: {curves_path}")\n'
    ]

    # Cell 37: Confusion matrix plot title
    nb['cells'][37]['source'] = [
        '# Section 19: Confusion Matrix\n',
        'if test_preds is not None and y_test is not None:\n',
        '    cm = confusion_matrix(y_test, test_preds)\n',
        '\n',
        '    plt.figure(figsize=(9, 7))\n',
        '    sns.heatmap(\n',
        '        cm,\n',
        '        annot=True,\n',
        '        fmt="d",\n',
        '        cmap="Blues",\n',
        '        xticklabels=DIGIT_CLASSES,\n',
        '        yticklabels=DIGIT_CLASSES,\n',
        '        cbar=True\n',
        '    )\n',
        '    plt.title(f"Confusion Matrix: EfficientNetB0 + BiLSTM (Attn Pooling) ({DATASET_MODE})", fontsize=13, fontweight="bold")\n',
        '    plt.xlabel("Predicted Digit Class", fontsize=11)\n',
        '    plt.ylabel("True Digit Class", fontsize=11)\n',
        '    plt.tight_layout()\n',
        '\n',
        '    cm_path = RESULTS_DIR / f"confusion_matrix_{DATASET_MODE}.png"\n',
        '    plt.savefig(cm_path, dpi=200)\n',
        '    plt.show()\n',
        '    print(f"Confusion matrix saved to: {cm_path}")\n',
        'else:\n',
        '    print(f"DATASET_MODE: {DATASET_MODE} - Confusion matrix skipped (no test split)")\n'
    ]

    # Cell 38: Markdown Save Results
    nb['cells'][38]['source'] = [
        '## 20. Save Results\n',
        'Exporting test predictions CSV and the consolidated experiment metrics JSON file to `results/efficientnetb0_bilstm_attention_pooling_{DATASET_MODE}/`.\n'
    ]

    # Cell 39: Save Results code
    nb['cells'][39]['source'] = [
        '# Section 20: Save Results Artifacts\n',
        'if test_preds is not None and "test" in df_manifest["split"].values:\n',
        '    test_manifest = df_manifest[df_manifest["split"] == "test"].copy().reset_index(drop=True)\n',
        '    test_manifest["predicted_digit"] = [ID_TO_CLASS[p] for p in test_preds]\n',
        '    test_manifest["predicted_id"] = test_preds\n',
        '    test_manifest["correct"] = (test_manifest["digit_id"] == test_manifest["predicted_id"])\n',
        '\n',
        '    test_predictions_csv = RESULTS_DIR / f"test_predictions_{DATASET_MODE}.csv"\n',
        '    test_manifest[["speaker", "base_speaker", "digit", "digit_id", "predicted_digit", "predicted_id", "correct"]].to_csv(\n',
        '        test_predictions_csv, index=False\n',
        '    )\n',
        '    print(f"Test predictions saved to: {test_predictions_csv}")\n',
        '\n',
        'final_metrics = {\n',
        '    "model_name": "EfficientNetB0_BiLSTM_AttentionPooling",\n',
        '    "temporal_head": f"BiLSTM_{LSTM_UNITS}units_AttentionPooling",\n',
        '    "dataset_mode": DATASET_MODE,\n',
        '    "dataset_dir": str(DATA_DIR),\n',
        '    "seed": SEED,\n',
        '    "num_train_folders": len(train_speakers),\n',
        '    "num_base_train_speakers": len(base_train_speakers),\n',
        '    "num_val_folders": len(val_speakers),\n',
        '    "num_base_val_speakers": len(base_val_speakers),\n',
        '    "num_test_folders": len(test_speakers),\n',
        '    "num_base_test_speakers": len(base_test_speakers),\n',
        '    "stage1": {\n',
        '        "best_epoch": stage1_best_epoch,\n',
        '        "best_val_loss": stage1_best_val_loss,\n',
        '        "best_val_accuracy": stage1_best_val_acc,\n',
        '        "learning_rate": STAGE1_LR,\n',
        '        "max_epochs": STAGE1_MAX_EPOCHS,\n',
        '        "patience": STAGE1_PATIENCE,\n',
        '    },\n',
        '    "stage2": {\n',
        '        "best_epoch": stage2_best_epoch,\n',
        '        "best_val_loss": stage2_best_val_loss,\n',
        '        "best_val_accuracy": stage2_best_val_acc,\n',
        '        "fine_tune_fraction": FINE_TUNE_FRACTION,\n',
        '        "learning_rate": STAGE2_LR,\n',
        '        "max_epochs": STAGE2_MAX_EPOCHS,\n',
        '        "patience": STAGE2_PATIENCE,\n',
        '    },\n',
        '    "final_validation": {\n',
        '        "loss": float(val_loss),\n',
        '        "accuracy": float(val_acc),\n',
        '    },\n',
        '    "final_test": {\n',
        '        "accuracy": float(test_acc) if test_acc is not None else None,\n',
        '        "macro_precision": float(test_prec) if test_prec is not None else None,\n',
        '        "macro_recall": float(test_rec) if test_rec is not None else None,\n',
        '        "macro_f1": float(test_f1) if test_f1 is not None else None,\n',
        '        "correct_predictions": int((test_preds == y_test).sum()) if test_preds is not None else None,\n',
        '        "total_test_samples": int(len(y_test)) if y_test is not None else None,\n',
        '    } if test_acc is not None else "DISABLED",\n',
        '    "parameters": {\n',
        '        "total_params": int(model.count_params()),\n',
        '        "stage2_trainable_params": int(stage2_trainable_params),\n',
        '    }\n',
        '}\n',
        '\n',
        'metrics_json_path = RESULTS_DIR / f"metrics_{DATASET_MODE}.json"\n',
        'with open(metrics_json_path, "w") as f:\n',
        '    json.dump(final_metrics, f, indent=2)\n',
        'print(f"Final metrics JSON saved to: {metrics_json_path}")\n'
    ]

    # Cell 40: Markdown Comparison Table
    nb['cells'][40]['source'] = [
        '## 21. Final Experiment Summary\n',
        'Architectural comparison table across the core temporal modeling paradigms:\n',
        '\n',
        '| Architectural Component | EfficientNetB0 + 4-Block Transformer (GAP) | EfficientNetB0 + 4-Block Transformer (Temporal Attn) | EfficientNetB0 + BiLSTM + Attention Pooling (This Experiment) |\n',
        '| :--- | :--- | :--- | :--- |\n',
        '| **Visual Frontend** | EfficientNetB0 (ImageNet weights) | EfficientNetB0 (ImageNet weights) | **EfficientNetB0 (ImageNet weights)** |\n',
        '| **Temporal Modeling** | 4× Transformer Encoder Blocks | 4× Transformer Encoder Blocks | **Bidirectional LSTM (128 units/dir)** |\n',
        '| **Inductive Bias** | Weak / Data-hungry | Weak / Data-hungry | **Strong Sequential Inductive Bias** |\n',
        '| **Sequence Pooling** | GlobalAveragePooling1D | Learnable Attention Pooling | **Learnable Temporal Attention Pooling** |\n',
        '| **Projection Dimension** | 256 | 256 | **256** |\n',
        '| **Stage 1 Protocol** | Frozen CNN, Adam (lr=1e-4), EarlyStopping | Frozen CNN, Adam (lr=1e-4), EarlyStopping | **Frozen CNN, Adam (lr=1e-4), EarlyStopping** |\n',
        '| **Stage 2 Protocol** | Unfreeze top 20%, BatchNorm frozen, Adam (lr=1e-5) | Unfreeze top 20%, BatchNorm frozen, Adam (lr=1e-5) | **Unfreeze top 20%, BatchNorm frozen, Adam (lr=1e-5)** |\n',
        '| **Loss Function** | Label Smoothing ($0.1$) | Label Smoothing ($0.1$) | **Label Smoothing ($0.1$)** |\n',
        '| **Dataset Mode** | 80/20 & 100/3/3 | 80/20 & 100/3/3 | **80/20 Split (24 base train / 6 base val)** |\n'
    ]

    # Cell 41: Final printout
    nb['cells'][41]['source'] = [
        '# Section 21: Final Experiment Summary Printout\n',
        'print("=" * 60)\n',
        'print(f"FINAL EVALUATION SUMMARY: EfficientNetB0 + BiLSTM (Attn Pooling) [{DATASET_MODE}]")\n',
        'print("=" * 60)\n',
        'if test_acc is not None:\n',
        '    print(f"Test Accuracy:        {test_acc * 100:.2f}%")\n',
        '    print(f"Macro Precision:      {test_prec:.4f}")\n',
        '    print(f"Macro Recall:         {test_rec:.4f}")\n',
        '    print(f"Macro F1-Score:       {test_f1:.4f}")\n',
        'else:\n',
        '    print(f"Test Evaluation:      DISABLED ({DATASET_MODE} mode)")\n',
        'print(f"Validation Accuracy:  {val_acc * 100:.2f}%")\n',
        'print(f"Validation Loss:      {val_loss:.4f}")\n',
        'print(f"Total Parameters:     {model.count_params():,}")\n',
        'print(f"Trainable Parameters: {stage2_trainable_params:,}")\n',
        'print("=" * 60)\n'
    ]

    # Clean execution counts and outputs
    for cell in nb['cells']:
        if cell['cell_type'] == 'code':
            cell['execution_count'] = None
            cell['outputs'] = []

    out_path = Path('notebooks/13_efficientnetb0_bilstm_attention_pooling_experiment.ipynb')
    with open(out_path, 'w') as f:
        json.dump(nb, f, indent=1)

    print(f'Successfully created {out_path} with {len(nb["cells"])} cells!')

if __name__ == '__main__':
    main()
