import json
from pathlib import Path

# 1. Update notebooks/05_model_training_baseline.ipynb
nb5_path = Path("notebooks/05_model_training_baseline.ipynb")
with open(nb5_path, "r", encoding="utf-8") as f:
    nb5 = json.load(f)

new_nb5_cell4_source = [
    "# Section 2: Configuration & DataLoader\n",
    "NOTEBOOK_DIR = Path.cwd()\n",
    "PROJECT_ROOT = NOTEBOOK_DIR.parent if NOTEBOOK_DIR.name == \"notebooks\" else NOTEBOOK_DIR\n",
    "\n",
    "# Dataset directories: easily switchable by pointing or replacing data/processed/train, val, test\n",
    "DATA_DIR = PROJECT_ROOT / \"data\" / \"processed\"\n",
    "TRAIN_DIR = DATA_DIR / \"train\"\n",
    "VAL_DIR = DATA_DIR / \"val\"\n",
    "TEST_DIR = DATA_DIR / \"test\"\n",
    "\n",
    "RESULTS_DIR = PROJECT_ROOT / \"results\" / \"dlib\"\n",
    "MODELS_DIR = PROJECT_ROOT / \"results\" / \"models\"\n",
    "MODELS_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "NUM_CLASSES = 11\n",
    "NUM_FRAMES = 30\n",
    "TARGET_WIDTH = 96\n",
    "TARGET_HEIGHT = 96\n",
    "CHANNELS = 3\n",
    "BATCH_SIZE = 16\n",
    "\n",
    "CNN_FEATURE_DIM = 64\n",
    "RNN_HIDDEN_UNITS = 64\n",
    "RNN_LAYERS = 1\n",
    "DROPOUT_RATE = 0.3\n",
    "LEARNING_RATE = 1e-4\n",
    "MAX_EPOCHS = 100\n",
    "PATIENCE = 15\n",
    "RE_TRAIN = True  # Set to True to re-train all models from scratch\n",
    "\n",
    "EXPECTED_DIGITS = [f\"d{i}\" for i in range(11)]\n",
    "CLASS_TO_ID = {d: i for i, d in enumerate(EXPECTED_DIGITS)}\n",
    "ID_TO_CLASS = {i: d for i, d in enumerate(EXPECTED_DIGITS)}\n",
    "\n",
    "def natural_sort_key(p):\n",
    "    m = re.search(r\"(\\d+)\", Path(p).stem)\n",
    "    return int(m.group(1)) if m else 0\n",
    "\n",
    "def sample_frame_paths(fpaths, target=NUM_FRAMES):\n",
    "    n = len(fpaths)\n",
    "    return [str(fpaths[i]) for i in np.round(np.linspace(0, n - 1, target)).astype(int)]\n",
    "\n",
    "def load_single_frame(path_tensor):\n",
    "    raw = tf.io.read_file(path_tensor)\n",
    "    img = tf.image.decode_jpeg(raw, channels=CHANNELS)\n",
    "    img = tf.image.resize(img, [TARGET_HEIGHT, TARGET_WIDTH], method=tf.image.ResizeMethod.BILINEAR)\n",
    "    img = tf.cast(img, tf.float32) / 255.0\n",
    "    img.set_shape([TARGET_HEIGHT, TARGET_WIDTH, CHANNELS])\n",
    "    return img\n",
    "\n",
    "def load_video_frames(paths_tensor):\n",
    "    frames = tf.map_fn(\n",
    "        fn=load_single_frame,\n",
    "        elems=paths_tensor,\n",
    "        fn_output_signature=tf.TensorSpec(shape=[TARGET_HEIGHT, TARGET_WIDTH, CHANNELS], dtype=tf.float32)\n",
    "    )\n",
    "    frames.set_shape([NUM_FRAMES, TARGET_HEIGHT, TARGET_WIDTH, CHANNELS])\n",
    "    return frames\n",
    "\n",
    "def index_split_utterances(split_dir, split_name):\n",
    "    records = []\n",
    "    speakers = sorted([d.name for d in split_dir.iterdir() if d.is_dir() and not d.name.startswith('.')])\n",
    "    for spk in speakers:\n",
    "        for digit in EXPECTED_DIGITS:\n",
    "            ddir = split_dir / spk / digit\n",
    "            if not ddir.exists():\n",
    "                continue\n",
    "            fpaths = sorted([f for f in ddir.glob('*.jpg')], key=natural_sort_key)\n",
    "            if len(fpaths) > 0:\n",
    "                records.append({\n",
    "                    'speaker': spk,\n",
    "                    'digit': digit,\n",
    "                    'frame_paths': sample_frame_paths(fpaths, NUM_FRAMES),\n",
    "                    'digit_id': CLASS_TO_ID[digit],\n",
    "                    'split': split_name\n",
    "                })\n",
    "    return pd.DataFrame(records)\n",
    "\n",
    "train_df = index_split_utterances(TRAIN_DIR, 'train')\n",
    "val_df = index_split_utterances(VAL_DIR, 'val')\n",
    "test_df = index_split_utterances(TEST_DIR, 'test')\n",
    "\n",
    "def create_tf_dataset_from_records(df_subset, is_training=False, shuffle=True):\n",
    "    all_paths = list(df_subset['frame_paths'])\n",
    "    all_labels = list(df_subset['digit_id'])\n",
    "    ds = tf.data.Dataset.from_tensor_slices((all_paths, all_labels))\n",
    "    ds = ds.map(lambda p, l: (load_video_frames(p), tf.cast(l, tf.int32)), num_parallel_calls=tf.data.AUTOTUNE)\n",
    "    ds = ds.cache()\n",
    "    if is_training and shuffle:\n",
    "        ds = ds.shuffle(len(df_subset), seed=SEED)\n",
    "    ds = ds.batch(BATCH_SIZE, drop_remainder=False).prefetch(tf.data.AUTOTUNE)\n",
    "    return ds\n",
    "\n",
    "train_dataset = create_tf_dataset_from_records(train_df, is_training=True, shuffle=True)\n",
    "val_dataset = create_tf_dataset_from_records(val_df, is_training=False, shuffle=False)\n",
    "test_dataset = create_tf_dataset_from_records(test_df, is_training=False, shuffle=False)\n",
    "\n",
    "print(f\"Loaded from: Train={TRAIN_DIR}, Val={VAL_DIR}, Test={TEST_DIR}\")\n",
    "print(f\"Speakers: {train_df['speaker'].nunique()} train, {val_df['speaker'].nunique()} val, {test_df['speaker'].nunique()} test\")\n",
    "print(f\"Utterances: {len(train_df)} train, {len(val_df)} val, {len(test_df)} test\")\n",
    "print(f\"Batches: {len(train_dataset)} train | {len(val_dataset)} val | {len(test_dataset)} test\")\n"
]

nb5['cells'][4]['source'] = new_nb5_cell4_source
with open(nb5_path, "w", encoding="utf-8") as f:
    json.dump(nb5, f, indent=1)
print("Updated 05_model_training_baseline.ipynb successfully!")

# 2. Update notebooks/06_pretrained_phase1_baseline.ipynb
nb6_path = Path("notebooks/06_pretrained_phase1_baseline.ipynb")
with open(nb6_path, "r", encoding="utf-8") as f:
    nb6 = json.load(f)

new_nb6_cell2_source = [
    "# Section 1: Environment & Imports\n",
    "import os\n",
    "import sys\n",
    "import re\n",
    "import json\n",
    "import time\n",
    "import random\n",
    "from pathlib import Path\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report\n",
    "from PIL import Image\n",
    "\n",
    "import tensorflow as tf\n",
    "import keras\n",
    "\n",
    "# Reproducibility Seed\n",
    "SEED = 42\n",
    "random.seed(SEED)\n",
    "np.random.seed(SEED)\n",
    "tf.random.set_seed(SEED)\n",
    "\n",
    "NOTEBOOK_DIR = Path.cwd()\n",
    "PROJECT_ROOT = NOTEBOOK_DIR.parent if NOTEBOOK_DIR.name == \"notebooks\" else NOTEBOOK_DIR\n",
    "\n",
    "# Dataset directories: easily switchable by pointing or replacing data/processed/train, val, test\n",
    "DATA_DIR = PROJECT_ROOT / \"data\" / \"processed\"\n",
    "TRAIN_DIR = DATA_DIR / \"train\"\n",
    "VAL_DIR = DATA_DIR / \"val\"\n",
    "TEST_DIR = DATA_DIR / \"test\"\n",
    "\n",
    "RESULTS_DIR = PROJECT_ROOT / \"results\" / \"pretrained_phase1\"\n",
    "RESULTS_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Hyperparameters & Constants\n",
    "NUM_CLASSES = 11\n",
    "NUM_FRAMES = 30\n",
    "FRAME_WIDTH = 96\n",
    "FRAME_HEIGHT = 96\n",
    "FRAME_CHANNELS = 3\n",
    "BATCH_SIZE = 16\n",
    "MAX_EPOCHS = 80\n",
    "LEARNING_RATE = 1e-4\n",
    "PATIENCE = 15\n",
    "RNN_UNITS = 64\n",
    "DROPOUT_RATE = 0.3\n",
    "\n",
    "DIGIT_CLASSES = [f\"d{i}\" for i in range(NUM_CLASSES)]\n",
    "CLASS_TO_ID = {d: i for i, d in enumerate(DIGIT_CLASSES)}\n",
    "ID_TO_CLASS = {i: d for i, d in enumerate(DIGIT_CLASSES)}\n",
    "\n",
    "print(f\"TensorFlow Version: {tf.__version__}\")\n",
    "print(f\"Keras Version:      {keras.__version__}\")\n",
    "print(f\"Seed:               {SEED}\")\n",
    "print(f\"Project Root:       {PROJECT_ROOT}\")\n",
    "print(f\"Train Directory:    {TRAIN_DIR}\")\n",
    "print(f\"Val Directory:      {VAL_DIR}\")\n",
    "print(f\"Test Directory:     {TEST_DIR}\")\n",
    "print(f\"Results Directory:  {RESULTS_DIR}\")\n"
]

new_nb6_cell4_source = [
    "# Section 2: Canonical Speaker-Independent Split Discovery\n",
    "train_speakers = sorted([d.name for d in TRAIN_DIR.iterdir() if d.is_dir() and not d.name.startswith('.')])\n",
    "val_speakers = sorted([d.name for d in VAL_DIR.iterdir() if d.is_dir() and not d.name.startswith('.')])\n",
    "test_speakers = sorted([d.name for d in TEST_DIR.iterdir() if d.is_dir() and not d.name.startswith('.')])\n",
    "all_speakers = sorted(train_speakers + val_speakers + test_speakers)\n",
    "\n",
    "print(f\"Total Speakers Discovered ({len(all_speakers)})\")\n",
    "print(f\"Train Speakers ({len(train_speakers)}): {train_speakers[:10]}... (total {len(train_speakers)})\")\n",
    "print(f\"Validation Speakers ({len(val_speakers)}): {val_speakers}\")\n",
    "print(f\"Unseen Test Speakers ({len(test_speakers)}): {test_speakers}\")\n",
    "\n",
    "# Strict verification of mutual exclusivity and completeness\n",
    "assert len(set(train_speakers) & set(val_speakers)) == 0, \"Train-Val overlap detected!\"\n",
    "assert len(set(train_speakers) & set(test_speakers)) == 0, \"Train-Test overlap detected!\"\n",
    "assert len(set(val_speakers) & set(test_speakers)) == 0, \"Val-Test overlap detected!\"\n",
    "\n",
    "# Verify that test and val speakers do not contain augmented variants\n",
    "for s in test_speakers:\n",
    "    assert \"_aug\" not in s, f\"Leaked augmented speaker {s} found in test partition!\"\n",
    "for s in val_speakers:\n",
    "    assert \"_aug\" not in s, f\"Leaked augmented speaker {s} found in val partition!\"\n",
    "\n",
    "# Persist partition specification\n",
    "speaker_split_data = {\n",
    "    \"random_seed\": SEED,\n",
    "    \"num_train_speakers\": len(train_speakers),\n",
    "    \"num_val_speakers\": len(val_speakers),\n",
    "    \"num_test_speakers\": len(test_speakers),\n",
    "    \"train_speakers\": train_speakers,\n",
    "    \"val_speakers\": val_speakers,\n",
    "    \"test_speakers\": test_speakers\n",
    "}\n",
    "with open(RESULTS_DIR / \"speaker_split.json\", \"w\") as f:\n",
    "    json.dump(speaker_split_data, f, indent=2)\n",
    "\n",
    "print(f\"Saved canonical speaker partition metadata to: {RESULTS_DIR / 'speaker_split.json'}\")\n"
]

new_nb6_cell6_source = [
    "# Section 3: Manifest Indexing & Temporal Standardization\n",
    "def natural_sort_key(p):\n",
    "    m = re.search(r\"(\\d+)\", Path(p).stem)\n",
    "    return int(m.group(1)) if m else 0\n",
    "\n",
    "def sample_or_interpolate_frames(fpaths, target=NUM_FRAMES):\n",
    "    n = len(fpaths)\n",
    "    if n == target:\n",
    "        indices = list(range(target))\n",
    "    else:\n",
    "        indices = np.round(np.linspace(0, n - 1, target)).astype(int)\n",
    "    return [str(fpaths[i]) for i in indices]\n",
    "\n",
    "utterances = []\n",
    "split_dirs = {\"train\": TRAIN_DIR, \"val\": VAL_DIR, \"test\": TEST_DIR}\n",
    "\n",
    "for split_name, s_dir in split_dirs.items():\n",
    "    speakers = sorted([d.name for d in s_dir.iterdir() if d.is_dir() and not d.name.startswith('.')])\n",
    "    for spk in speakers:\n",
    "        for digit in DIGIT_CLASSES:\n",
    "            digit_dir = s_dir / spk / digit\n",
    "            if not digit_dir.exists():\n",
    "                continue\n",
    "            frames = sorted(list(digit_dir.glob(\"*.jpg\")), key=natural_sort_key)\n",
    "            if len(frames) == 0:\n",
    "                continue\n",
    "            sampled_frames = sample_or_interpolate_frames(frames, NUM_FRAMES)\n",
    "            utterances.append({\n",
    "                \"speaker\": spk,\n",
    "                \"digit\": digit,\n",
    "                \"digit_id\": CLASS_TO_ID[digit],\n",
    "                \"split\": split_name,\n",
    "                \"raw_frame_count\": len(frames),\n",
    "                \"sampled_frame_paths\": sampled_frames\n",
    "            })\n",
    "\n",
    "df_manifest = pd.DataFrame(utterances)\n",
    "print(f\"Total Utterances Indexed: {len(df_manifest)}\")\n",
    "print(f\"  Training Split:   {len(df_manifest[df_manifest['split']=='train'])} utterances ({len(train_speakers)} speakers)\")\n",
    "print(f\"  Validation Split: {len(df_manifest[df_manifest['split']=='val'])} utterances ({len(val_speakers)} speakers)\")\n",
    "print(f\"  Test Split:       {len(df_manifest[df_manifest['split']=='test'])} utterances ({len(test_speakers)} speakers)\")\n",
    "\n",
    "df_manifest[[\"speaker\", \"digit\", \"digit_id\", \"split\", \"raw_frame_count\"]].to_csv(\n",
    "    RESULTS_DIR / \"utterance_manifest.csv\", index=False\n",
    ")\n",
    "print(f\"Saved utterance manifest to: {RESULTS_DIR / 'utterance_manifest.csv'}\")\n",
    "\n",
    "# Frame count distribution summary\n",
    "raw_counts = df_manifest['raw_frame_count']\n",
    "print(f\"\\nRaw Frame Counts: Min={raw_counts.min()}, Max={raw_counts.max()}, Median={raw_counts.median():.0f}, Mean={raw_counts.mean():.1f}\")\n",
    "df_manifest.groupby(\"split\")[\"raw_frame_count\"].describe()\n"
]

nb6['cells'][2]['source'] = new_nb6_cell2_source
nb6['cells'][4]['source'] = new_nb6_cell4_source
nb6['cells'][6]['source'] = new_nb6_cell6_source

with open(nb6_path, "w", encoding="utf-8") as f:
    json.dump(nb6, f, indent=1)
print("Updated 06_pretrained_phase1_baseline.ipynb successfully!")
